layout_spectrum: 0.7820326
typography_spectrum: 0.9696891
color:
  saturation: 0.5400895
  lightness: 0.1364631
  brandStrength: 0.309647
  rhythmicContrast: 0.7430333
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: DozzerMedia
